freebsd_build_task:

  freebsd_instance:
    matrix:
      image_family: freebsd-12-1-snap
      image_family: freebsd-11-3-snap
    cpu: 4
    memory: 8G

  env:
    DEPENDENCIES: automake libtool gmake gcc wget openssl
                  python3 py37-six py37-sphinx py37-openssl
    matrix:
      COMPILER: gcc
      COMPILER: clang

  prepare_script:
    - sysctl -w kern.coredump=0
    - pkg update -f
    - pkg install -y ${DEPENDENCIES}

  configure_script:
    - ./boot.sh
    - ./configure CC=${COMPILER} MAKE=gmake OVS_CFLAGS='-Wall' --enable-Werror
                  || { cat config.log; exit 1; }

  build_script:
    - gmake -j8

  check_script:
    - gmake -j8 check TESTSUITEFLAGS=-j8 RECHECK=yes
                || { cat ./tests/testsuite.log; exit 1; }
